"""empty message

Revision ID: 8e698597197d
Revises: af9442a38b62
Create Date: 2021-07-17 14:07:22.634701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e698597197d'
down_revision = 'af9442a38b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('density', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('density'),
    sa.UniqueConstraint('density'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('people', sa.Column('planets', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'people', ['planets'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'planets')
    op.drop_table('planet')
    # ### end Alembic commands ###
