"""empty message

Revision ID: b0d08363582d
Revises: 8e698597197d
Create Date: 2021-07-17 14:25:59.193203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d08363582d'
down_revision = '8e698597197d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('people_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'people', ['people_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'people_id')
    # ### end Alembic commands ###
